### ISSUE TITLE
Rate limits

### ISSUE THREAD

**Issue by richardlau** [nodejs/github-bot#374]
According to the bot's logs, we're now hitting rate limits, e.g.
```console
{"name":"bot","hostname":"infra-rackspace-debian8-x64-1","pid":15899,"req_id":"e62c49d0-bbaa-11ed-9410-77b81a7c3334","identifier":"node-test-linux-ubuntu1804-64","event":"end","level":50,"err":{"message":"API rate limit exceeded for 23.253.100.79. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)","name":"HttpError","stack":"HttpError: API rate limit exceeded for 23.253.100.79. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)\n    at /home/iojs/github-bot/node_modules/@octokit/request/dist-node/index.js:86:21\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)\n    at async Object.next (/home/iojs/github-bot/node_modules/@octokit/plugin-paginate-rest/dist-node/index.js:112:28)\n    at async findLatestCommitInPr (/home/iojs/github-bot/lib/push-jenkins-update.js:88:23)","code":403},"msg":"Error while handling Jenkins end event","time":"2023-03-05T23:10:20.025Z","v":0}
```

Possibly related to https://github.com/nodejs/github-bot/pull/371#discussion_r1125708792?

**Comment by phillipj** [comment]
Good catch.

We're probably not doing authenticated requests anymore since the ordinary
Github client isn't used, hence lower request limits. I did not have that
aspect in mind when raising the comment referred to.

**Comment by Trott** [comment]
I'll push a fix if someone hasn't done it already.
