### ISSUE TITLE
Bot failing to start: `TypeError: glob.sync is not a function`

### ISSUE THREAD

**Issue by richardlau** [nodejs/github-bot#376]
@tniessen [reports](https://openjs-foundation.slack.com/archives/C03BJP63CH0/p1678138229956679?thread_ts=1678104091.867669&cid=C03BJP63CH0) that Jenkins status is still not being posted to pull requests. 

Looking at https://ci.nodejs.org/job/post-build-status-update runs, e.g. https://ci.nodejs.org/job/post-build-status-update/1837783/flowGraphTable/, I can see that although the jobs are green, the HTTP request to the bot has failed:
![image](https://user-images.githubusercontent.com/5445507/223419928-cb5b0042-2c89-4ff5-9c59-cad0e69eb2dc.png)

https://ci.nodejs.org/job/post-build-status-update/1837783/execution/node/17/
```console
hudson.AbortException: Fail: Status code 408 is not in the accepted range: 100:399
```

If I log into the server for the github-bot, I can see that the service isn't running:
```console
root@infra-rackspace-debian8-x64-1:~# systemctl status github-bot
● github-bot.service - github-bot
   Loaded: loaded (/lib/systemd/system/github-bot.service; enabled)
   Active: activating (auto-restart) (Result: exit-code) since Tue 2023-03-07 12:19:55 UTC; 41ms ago
  Process: 25524 ExecStart=/usr/bin/node server.js (code=exited, status=1/FAILURE)
 Main PID: 25524 (code=exited, status=1/FAILURE)

Mar 07 12:19:55 infra-rackspace-debian8-x64-1 systemd[1]: github-bot.service: main process exited, code=exited, status=1/FAILURE
Mar 07 12:19:55 infra-rackspace-debian8-x64-1 systemd[1]: Unit github-bot.service entered failed state.
root@infra-rackspace-debian8-x64-1:~#
```

and from the syslog:

```console
Mar  7 12:13:26 infra-rackspace-debian8-x64-1 systemd[1]: Started github-bot.
Mar  7 12:13:26 infra-rackspace-debian8-x64-1 node[24754]: /home/iojs/github-bot/server.js:13
Mar  7 12:13:26 infra-rackspace-debian8-x64-1 node[24754]: glob.sync(scriptsToLoad).forEach((file) => {
Mar  7 12:13:26 infra-rackspace-debian8-x64-1 node[24754]: ^
Mar  7 12:13:26 infra-rackspace-debian8-x64-1 node[24754]: TypeError: glob.sync is not a function
Mar  7 12:13:26 infra-rackspace-debian8-x64-1 node[24754]: at Object.<anonymous> (/home/iojs/github-bot/server.js:13:6)
Mar  7 12:13:26 infra-rackspace-debian8-x64-1 node[24754]: at Module._compile (internal/modules/cjs/loader.js:1063:30)
Mar  7 12:13:26 infra-rackspace-debian8-x64-1 node[24754]: at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
Mar  7 12:13:26 infra-rackspace-debian8-x64-1 node[24754]: at Module.load (internal/modules/cjs/loader.js:928:32)
Mar  7 12:13:26 infra-rackspace-debian8-x64-1 node[24754]: at Function.Module._load (internal/modules/cjs/loader.js:769:14)
Mar  7 12:13:26 infra-rackspace-debian8-x64-1 node[24754]: at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
Mar  7 12:13:26 infra-rackspace-debian8-x64-1 node[24754]: at internal/main/run_main_module.js:17:47
Mar  7 12:13:26 infra-rackspace-debian8-x64-1 systemd[1]: github-bot.service: main process exited, code=exited, status=1/FAILURE
Mar  7 12:13:26 infra-rackspace-debian8-x64-1 systemd[1]: Unit github-bot.service entered failed state.
```

**Comment by richardlau** [comment]
https://github.com/nodejs/github-bot/pull/372 is the most likely suspect. cc @Trott

**Comment by richardlau** [comment]
PR (untested): https://github.com/nodejs/github-bot/pull/377

**Comment by richardlau** [comment]
bot still fails to start. Now getting:
```console
Mar  7 17:15:12 infra-rackspace-debian8-x64-1 systemd[1]: Starting github-bot...
Mar  7 17:15:12 infra-rackspace-debian8-x64-1 systemd[1]: Started github-bot.
Mar  7 17:15:13 infra-rackspace-debian8-x64-1 node[1969]: {"name":"bot","hostname":"infra-rackspace-debian8-x64-1","pid":1969,"level":30,"msg":"Loading: scripts/ping.js","time":"2023-03-07T17:15:13.365Z","v":0}
Mar  7 17:15:13 infra-rackspace-debian8-x64-1 node[1969]: internal/modules/cjs/loader.js:883
Mar  7 17:15:13 infra-rackspace-debian8-x64-1 node[1969]: throw err;
Mar  7 17:15:13 infra-rackspace-debian8-x64-1 node[1969]: ^
Mar  7 17:15:13 infra-rackspace-debian8-x64-1 node[1969]: Error: Cannot find module 'scripts/ping.js'
Mar  7 17:15:13 infra-rackspace-debian8-x64-1 node[1969]: Require stack:
Mar  7 17:15:13 infra-rackspace-debian8-x64-1 node[1969]: - /home/iojs/github-bot/server.js
Mar  7 17:15:13 infra-rackspace-debian8-x64-1 node[1969]: at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
Mar  7 17:15:13 infra-rackspace-debian8-x64-1 node[1969]: at Function.Module._load (internal/modules/cjs/loader.js:725:27)
Mar  7 17:15:13 infra-rackspace-debian8-x64-1 node[1969]: at Module.require (internal/modules/cjs/loader.js:952:19)
Mar  7 17:15:13 infra-rackspace-debian8-x64-1 node[1969]: at require (internal/modules/cjs/helpers.js:88:18)
Mar  7 17:15:13 infra-rackspace-debian8-x64-1 node[1969]: at /home/iojs/github-bot/server.js:15:3
Mar  7 17:15:13 infra-rackspace-debian8-x64-1 node[1969]: at Array.forEach (<anonymous>)
Mar  7 17:15:13 infra-rackspace-debian8-x64-1 node[1969]: at Object.<anonymous> (/home/iojs/github-bot/server.js:13:25)
Mar  7 17:15:13 infra-rackspace-debian8-x64-1 node[1969]: at Module._compile (internal/modules/cjs/loader.js:1063:30)
Mar  7 17:15:13 infra-rackspace-debian8-x64-1 node[1969]: at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
Mar  7 17:15:13 infra-rackspace-debian8-x64-1 node[1969]: at Module.load (internal/modules/cjs/loader.js:928:32) {
Mar  7 17:15:13 infra-rackspace-debian8-x64-1 node[1969]: code: 'MODULE_NOT_FOUND',
Mar  7 17:15:13 infra-rackspace-debian8-x64-1 node[1969]: requireStack: [ '/home/iojs/github-bot/server.js' ]
Mar  7 17:15:13 infra-rackspace-debian8-x64-1 node[1969]: }
Mar  7 17:15:13 infra-rackspace-debian8-x64-1 systemd[1]: github-bot.service: main process exited, code=exited, status=1/FAILURE
```

**Comment by richardlau** [comment]
I'm guessing we're somehow being affected by 
> More correct handling of `**` vs `./**`, following Bash semantics, where a `**` is followed one time only if it is not the first item in the pattern.

(https://github.com/isaacs/node-glob/blob/main/changelog.md#performance-and-algorithm-changes)

https://github.com/nodejs/github-bot/blob/7f2b20bb72d7f44d5d67a9298a1beadfee00620a/server.js#L9-L16

**Comment by Trott** [comment]
I would think we don't need `**` because there aren't any subdirectories in the `scripts` folder.

**Comment by Trott** [comment]
(A test that just ran `node server.js` would have found this.)

**Comment by richardlau** [comment]
I'm speculating that we're no longer getting paths prefixed with `./` back from glob.

**Comment by Trott** [comment]
Indeed, this fixes it:

```diff
diff --git a/server.js b/server.js
index b3aa5b6..db7a7a9 100644
--- a/server.js
+++ b/server.js
@@ -12,7 +12,7 @@ const { app, events } = require('./app')
 // load all the files in the scripts folder
 globSync(scriptsToLoad).forEach((file) => {
   logger.info('Loading:', file)
-  require(file)(app, events)
+  require(`./${file}`)(app, events)
 })
 
 app.listen(port, () => {
```

**Comment by richardlau** [comment]
https://github.com/isaacs/node-glob/issues/495

**Comment by richardlau** [comment]
Ah, there's a new `dotRelative` option https://github.com/isaacs/node-glob/pull/500

**Comment by richardlau** [comment]
Bot has started with https://github.com/nodejs/github-bot/pull/378
