### ISSUE TITLE
Bot is broken

### ISSUE THREAD

**Issue by richardlau** [nodejs/github-bot#412]
Looks like the bot isn't running -- it's failing to start:
```console
Jul 11 17:44:10 infra-rackspace-debian8-x64-1 systemd[1]: Starting github-bot...
Jul 11 17:44:10 infra-rackspace-debian8-x64-1 systemd[1]: Started github-bot.
Jul 11 17:44:10 infra-rackspace-debian8-x64-1 node[32482]: internal/modules/cjs/loader.js:883
Jul 11 17:44:10 infra-rackspace-debian8-x64-1 node[32482]: throw err;
Jul 11 17:44:10 infra-rackspace-debian8-x64-1 node[32482]: ^
Jul 11 17:44:10 infra-rackspace-debian8-x64-1 node[32482]: Error: Cannot find module 'node:events'
Jul 11 17:44:10 infra-rackspace-debian8-x64-1 node[32482]: Require stack:
Jul 11 17:44:10 infra-rackspace-debian8-x64-1 node[32482]: - /home/iojs/github-bot/node_modules/path-scurry/node_modules/minipass/dist/cjs/index.js
Jul 11 17:44:10 infra-rackspace-debian8-x64-1 node[32482]: - /home/iojs/github-bot/node_modules/path-scurry/dist/cjs/index.js
Jul 11 17:44:10 infra-rackspace-debian8-x64-1 node[32482]: - /home/iojs/github-bot/node_modules/glob/dist/cjs/src/glob.js
Jul 11 17:44:10 infra-rackspace-debian8-x64-1 node[32482]: - /home/iojs/github-bot/node_modules/glob/dist/cjs/src/index.js
Jul 11 17:44:10 infra-rackspace-debian8-x64-1 node[32482]: - /home/iojs/github-bot/server.js
Jul 11 17:44:10 infra-rackspace-debian8-x64-1 node[32482]: at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
Jul 11 17:44:10 infra-rackspace-debian8-x64-1 node[32482]: at Function.Module._load (internal/modules/cjs/loader.js:725:27)
Jul 11 17:44:10 infra-rackspace-debian8-x64-1 node[32482]: at Module.require (internal/modules/cjs/loader.js:952:19)
Jul 11 17:44:10 infra-rackspace-debian8-x64-1 node[32482]: at require (internal/modules/cjs/helpers.js:88:18)
Jul 11 17:44:10 infra-rackspace-debian8-x64-1 node[32482]: at Object.<anonymous> (/home/iojs/github-bot/node_modules/path-scurry/node_modules/minipass/dist/cjs/index.js:13:23)
Jul 11 17:44:10 infra-rackspace-debian8-x64-1 node[32482]: at Module._compile (internal/modules/cjs/loader.js:1063:30)
Jul 11 17:44:10 infra-rackspace-debian8-x64-1 node[32482]: at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
Jul 11 17:44:10 infra-rackspace-debian8-x64-1 node[32482]: at Module.load (internal/modules/cjs/loader.js:928:32)
Jul 11 17:44:10 infra-rackspace-debian8-x64-1 node[32482]: at Function.Module._load (internal/modules/cjs/loader.js:769:14)
Jul 11 17:44:10 infra-rackspace-debian8-x64-1 node[32482]: at Module.require (internal/modules/cjs/loader.js:952:19) {
Jul 11 17:44:10 infra-rackspace-debian8-x64-1 node[32482]: code: 'MODULE_NOT_FOUND',
Jul 11 17:44:10 infra-rackspace-debian8-x64-1 node[32482]: requireStack: [
Jul 11 17:44:10 infra-rackspace-debian8-x64-1 node[32482]: '/home/iojs/github-bot/node_modules/path-scurry/node_modules/minipass/dist/cjs/index.js',
Jul 11 17:44:10 infra-rackspace-debian8-x64-1 node[32482]: '/home/iojs/github-bot/node_modules/path-scurry/dist/cjs/index.js',
Jul 11 17:44:10 infra-rackspace-debian8-x64-1 node[32482]: '/home/iojs/github-bot/node_modules/glob/dist/cjs/src/glob.js',
Jul 11 17:44:10 infra-rackspace-debian8-x64-1 node[32482]: '/home/iojs/github-bot/node_modules/glob/dist/cjs/src/index.js',
Jul 11 17:44:10 infra-rackspace-debian8-x64-1 node[32482]: '/home/iojs/github-bot/server.js'
Jul 11 17:44:10 infra-rackspace-debian8-x64-1 node[32482]: ]
Jul 11 17:44:10 infra-rackspace-debian8-x64-1 node[32482]: }
Jul 11 17:44:10 infra-rackspace-debian8-x64-1 systemd[1]: github-bot.service: main process exited, code=exited, status=1/FAILURE
Jul 11 17:44:10 infra-rackspace-debian8-x64-1 systemd[1]: Unit github-bot.service entered failed state.
```

**Comment by richardlau** [comment]
Given the error stack, assume this is the glob update from https://github.com/nodejs/github-bot/pull/409

**Comment by richardlau** [comment]
According to [glob's package.json it needs Node.js 14.17.0](https://github.com/isaacs/node-glob/blob/8c371a3eaacaa0783c34bda13d32fca3219017d3/package.json#L96) -- we're currently stuck on 14.16.1 until we update the server https://github.com/nodejs/build/issues/3214

**Comment by Trott** [comment]
Aw, crud. Tests passed on 14.x. Will put us back down to glob@10.3.1 and hope it starts again....

**Comment by Trott** [comment]
Reverting the glob update seems to have fixed it.

The current version of @octokit/rest drops support for Node.js 14 so we're stuck on that dependency too until we can update on the server.
